In [7]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
df1 = pd.DataFrame(scores,
             columns=['國文', '英文', '數學', '地理', '歷史'],
             index=range(1,51))
df1.index.name='學號'
df1.columns.name="科目"
df1

科目   國文   英文  數學  地理   歷史
學號
1    65   69  92  78   95
2    65  100  62  63   80
3    97   72  87  97   66
4    82   58  73  67   52
5    84   73  75  80   62
6    85   50  84  82   65
7    87   97  79  52   92
8    75   60  57  54   99
9    53   71  79  88   64
10   96   71  88  70   75
11   72   79  79  85   82
12   66   75  89  71   87
13  100   96  86  80   99
14   69   74  83  88   65
15   85   73  66  72   91
16   62   68  76  66   71
17   83   79  76  63   79
18   80   55  94  92   88
19   55   97  58  92  100
20   54   54  83  75   84
21   79   59  70  98   94
22   55   63  89  50   66
23   87   63  88  86   62
24   97   52  96  89   56
25   60   74  90  54   84
26   91   55  50  78   79
27   89   61  72  57   69
28   93  100  63  76   65
29   57   84  97  84   61
30   85   77  52  81   99
31   58   58  92  91   86
32   95   86  96  74   93
33   63   68  77  85   67
34   98   90  74  72   93
35   99   89  79  68   87
36   76   81  78  62   94
37   94   61  95  61   70
38   53   63  93  99   67
39   98   69  60  91   59
40   77   85  78  78   85
41   73   79  62  90   97
42   80   83  88  65   76
43   58   78  57  79   87
44   64   53  73  79   52
45   59   68  71  86   62
46   54   69  95  57   75
47  100   60  78  82   91
48   65   67  97  51   68
49   74   88  90  60   90
50   83   92  77  69   68

In [13]:
from pandas import Series
def fun1(value:Series) -> Series:
    return pd.Series([value.max(),value.min(),value.median()],index=["最高分","最低分",'中間分'])

df2 = df1.apply(fun1)
df2

科目      國文     英文    數學    地理     歷史
最高分  100.0  100.0  97.0  99.0  100.0
最低分   53.0   50.0  50.0  50.0   52.0
中間分   78.0   71.5  79.0  78.0   79.0

In [12]:
#轉換成numpy
df1.values[:,0]

array([ 65,  65,  97,  82,  84,  85,  87,  75,  53,  96,  72,  66, 100,
        69,  85,  62,  83,  80,  55,  54,  79,  55,  87,  97,  60,  91,
        89,  93,  57,  85,  58,  95,  63,  98,  99,  76,  94,  53,  98,
        77,  73,  80,  58,  64,  59,  54, 100,  65,  74,  83])

In [15]:
#轉成csv
df2.to_csv('3年1班統計資料.csv')

In [17]:
#轉成excel
df2.to_excel('3年1班統計資料.xlsx')