In [2]:
import pandas as pd

df1 = pd.read_csv('各鄉鎮市區人口密度.csv')
df2 = df1.rename(columns={"statistic_yyy":"統計年",'site_id':'區域別','people_total':'年底人口數','area':'土地面積','population_density':'人口密度'})
df3 = df2.drop(0)
df4 = df3.reindex(index=range(1,371))
df4

     統計年     區域別   年底人口數     土地面積   人口密度
1    106  新北市板橋區  551480  23.1373  23835
2    106  新北市三重區  387484   16.317  23747
3    106  新北市中和區  413590   20.144  20532
4    106  新北市永和區  222585   5.7138  38956
5    106  新北市新莊區  416524  19.7383  21102
..   ...     ...     ...      ...    ...
366  106  連江縣北竿鄉    2360      9.9    238
367  106  連江縣莒光鄉    1624      4.7    346
368  106  連江縣東引鄉    1352      3.8    356
369  106    東沙群島      …      2.38     …
370  106    南沙群島      …    0.5045     …

[370 rows x 5 columns]

In [3]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    object
 3   土地面積    370 non-null    object
 4   人口密度    370 non-null    object
dtypes: object(5)
memory usage: 14.6+ KB

In [4]:
df4

     統計年     區域別   年底人口數     土地面積   人口密度
1    106  新北市板橋區  551480  23.1373  23835
2    106  新北市三重區  387484   16.317  23747
3    106  新北市中和區  413590   20.144  20532
4    106  新北市永和區  222585   5.7138  38956
5    106  新北市新莊區  416524  19.7383  21102
..   ...     ...     ...      ...    ...
366  106  連江縣北竿鄉    2360      9.9    238
367  106  連江縣莒光鄉    1624      4.7    346
368  106  連江縣東引鄉    1352      3.8    356
369  106    東沙群島      …      2.38     …
370  106    南沙群島      …    0.5045     …

[370 rows x 5 columns]

In [5]:
df4['年底人口數']

1      551480
2      387484
3      413590
4      222585
5      416524
        ...
366      2360
367      1624
368      1352
369        …
370        …
Name: 年底人口數, Length: 370, dtype: object

In [6]:
df4[['年底人口數','土地面積']]

      年底人口數     土地面積
1    551480  23.1373
2    387484   16.317
3    413590   20.144
4    222585   5.7138
5    416524  19.7383
..      ...      ...
366    2360      9.9
367    1624      4.7
368    1352      3.8
369      …      2.38
370      …    0.5045

[370 rows x 2 columns]

## replace(),astype()

In [14]:
serial1 = df4['年底人口數'].replace(to_replace='… ',value='0')
df4['年底人口數'] = serial1.astype(int)
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    int64
 3   土地面積    370 non-null    object
 4   人口密度    370 non-null    object
dtypes: int64(1), object(4)
memory usage: 14.6+ KB

In [23]:
serial2 = df4['人口密度'].replace(to_replace='… ',value='0')
df4['人口密度'] = serial2.astype(int)
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 370 entries, 1 to 370
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   統計年     370 non-null    object
 1   區域別     370 non-null    object
 2   年底人口數   370 non-null    int64
 3   土地面積    370 non-null    int64
 4   人口密度    370 non-null    int64
dtypes: int64(3), object(2)
memory usage: 14.6+ KB

In [24]:
df4

     統計年     區域別   年底人口數  土地面積   人口密度
1    106  新北市板橋區  551480    23  23835
2    106  新北市三重區  387484    16  23747
3    106  新北市中和區  413590    20  20532
4    106  新北市永和區  222585     5  38956
5    106  新北市新莊區  416524    19  21102
..   ...     ...     ...   ...    ...
366  106  連江縣北竿鄉    2360     9    238
367  106  連江縣莒光鄉    1624     4    346
368  106  連江縣東引鄉    1352     3    356
369  106    東沙群島       0     2      0
370  106    南沙群島       0     0      0

[370 rows x 5 columns]

## sort_values()

In [27]:
populations_df = df4.sort_values(by='年底人口數',ascending=False)
populations_df

     統計年     區域別   年底人口數  土地面積   人口密度
1    106  新北市板橋區  551480    23  23835
42   106  桃園市桃園區  440840    34  12666
5    106  新北市新莊區  416524    19  21102
3    106  新北市中和區  413590    20  20532
43   106  桃園市中壢區  405216    76   5296
..   ...     ...     ...   ...    ...
367  106  連江縣莒光鄉    1624     4    346
368  106  連江縣東引鄉    1352     3    356
364  106  金門縣烏坵鄉     685     1    571
369  106    東沙群島       0     2      0
370  106    南沙群島       0     0      0

[370 rows x 5 columns]

In [29]:
#人口數最多的前5個
populations_df.iloc[:5]
#人口數最少的5個
populations_df.iloc[-5:]

     統計年     區域別  年底人口數  土地面積  人口密度
367  106  連江縣莒光鄉   1624     4   346
368  106  連江縣東引鄉   1352     3   356
364  106  金門縣烏坵鄉    685     1   571
369  106    東沙群島      0     2     0
370  106    南沙群島      0     0     0

In [ ]:
## 排名rank

In [35]:
populations_df['人口數排名'] = populations_df['年底人口數'].rank(method='min',ascending=False)
populations_df

     統計年     區域別   年底人口數  土地面積   人口密度  人口數排名
1    106  新北市板橋區  551480    23  23835    1.0
42   106  桃園市桃園區  440840    34  12666    2.0
5    106  新北市新莊區  416524    19  21102    3.0
3    106  新北市中和區  413590    20  20532    4.0
43   106  桃園市中壢區  405216    76   5296    5.0
..   ...     ...     ...   ...    ...    ...
367  106  連江縣莒光鄉    1624     4    346  366.0
368  106  連江縣東引鄉    1352     3    356  367.0
364  106  金門縣烏坵鄉     685     1    571  368.0
369  106    東沙群島       0     2      0  369.0
370  106    南沙群島       0     0      0  369.0

[370 rows x 6 columns]

In [36]:
populations_df

     統計年     區域別   年底人口數  土地面積   人口密度  人口數排名
1    106  新北市板橋區  551480    23  23835    1.0
42   106  桃園市桃園區  440840    34  12666    2.0
5    106  新北市新莊區  416524    19  21102    3.0
3    106  新北市中和區  413590    20  20532    4.0
43   106  桃園市中壢區  405216    76   5296    5.0
..   ...     ...     ...   ...    ...    ...
367  106  連江縣莒光鄉    1624     4    346  366.0
368  106  連江縣東引鄉    1352     3    356  367.0
364  106  金門縣烏坵鄉     685     1    571  368.0
369  106    東沙群島       0     2      0  369.0
370  106    南沙群島       0     0      0  369.0

[370 rows x 6 columns]

In [40]:
populations_df[populations_df['土地面積'] > 100]

     統計年      區域別   年底人口數  土地面積  人口密度  人口數排名
6    106   新北市新店區  302089   120  2513   10.0
118  106   臺南市安南區  192224   107  1793   32.0
81   106   臺中市太平區  189066   120  1566   35.0
9    106   新北市三峽區  114926   191   600   62.0
312  106   臺東縣臺東市  105960   109   965   67.0
..   ...      ...     ...   ...   ...    ...
323  106   臺東縣延平鄉    3551   455     8  360.0
325  106   臺東縣達仁鄉    3518   306    11  361.0
305  106   屏東縣霧臺鄉    3246   278    12  362.0
158  106  高雄市那瑪夏區    3125   252    12  363.0
156  106   高雄市茂林區    1924   194    10  365.0

[80 rows x 6 columns]